Use ProyectoProgra3

--INSERTS 
Insert Into Estudiante (Nombre, Apellido1, Apellido2, Cedula)
Values  ('Jhonattan', 'Mora', 'Solano', 146321862),
		('Bryan', 'Gonzalez', 'Blanco', 114930604),
		('Sergio', 'Morales', 'Quiros', 125155565),
		('Sergio', 'Brenes', 'Perez', 156165164);

Select * from Estudiante


INSERT INTO TipoTelefono(DescripcionTipoTel)
VALUES ('Personal'),
		('Trabajo');	
			
Select * from TipoTelefono


INSERT INTO Telefono(IdTipoTelefono, Carnet, Numero)
VALUES (1, 1, 70372458),
		(2, 1, 22130021),
		(1, 2, 79842315),
		(1, 3, 54651351),
		(1, 4, 83038380),
		(2, 4, 22732606);

Select * from Telefono


INSERT INTO TipoEmail (DescripcionTipoEmail)
VALUES ('Personal'),
		('Trabajo');

Select * from TipoEmail


INSERT INTO Emails (IdTipoEmail, Carnet, Email)
VALUES (1, 1, 'cinque_cr@hotmail.com'),
		(2, 1, 'juegaplay@ps4.com'),
		(1, 2, 'bryang3001@hotmail.com'),
		(1, 3, 'sere.morales@hotmail.com'),
		(1, 4, 'sergiobrenes@gmail.com'),
		(2, 4, 'sergio.brenes@uh.com');

Select * from Emails
		

INSERT INTO Provincias (DescripcionProvincia)
VALUES ('San Jose'),
		('Alajuela'),
		('Cartago'),
		('Heredia'),
		('Guanacaste'),
		('Puntarenas'),
		('Limon');

Select * from Provincias


INSERT INTO Cantones (IdProvincia, DescripcionCanton)
values  ((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), 'Alajuelita'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), 'Aserrí'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), 'Curridabat'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), 'Desamparados'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), 'Escazú'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), 'Goicoechea'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), 'Montes de Oca'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), 'Mora'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), 'Perez Zeledon'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), 'Central'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), 'Santa Ana'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), 'Tibas'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), 'Vasquez de Coronado'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), 'Alajuela'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), 'San Ramón'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), 'Grecia'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), 'Atenas'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), 'Naranjo'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), 'Poás'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), 'Orotina'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), 'San Carlos'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), 'Zarcero'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), 'Valverde Vega'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), 'Upala'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), 'Los chiles'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), 'Gautuso'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Cartago'), 'Cartago'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Cartago'), 'Paraiso'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Cartago'), 'Jiménez'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Cartago'), 'Turrialba'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Cartago'), 'Oreamuno'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Cartago'), 'El Guarco'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Heredia'), 'Heredia'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Heredia'), 'Barva'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Heredia'), 'Santo Domingo'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Heredia'), 'Santa Barbara'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Heredia'), 'San Rafael'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Heredia'), 'San Isidro'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Heredia'), 'Belen'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Heredia'), 'Sarapiquí'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Guanacaste'), 'Liberia'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Guanacaste'), 'Santa Cruz'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Guanacaste'), 'Bagaces'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Guanacaste'), 'Carrillo'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Guanacaste'), 'Cañas'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Guanacaste'), 'Abangares'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Guanacaste'), 'Tilaran'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Guanacaste'), 'Nandayure'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Guanacaste'), 'La Cruz'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Puntarenas'), 'Puntarenas'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Puntarenas'), 'Esparza'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Puntarenas'), 'Bueno Aires'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Puntarenas'), 'Osa'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Puntarenas'), 'Quepos'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Puntarenas'), 'Golfito'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Puntarenas'), 'Coto Brus'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Puntarenas'), 'Parrita'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Puntarenas'), 'Corredores'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Puntarenas'), 'Garabito'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Limon'), 'Limon'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Limon'), 'Pococi'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Limon'), 'Siquirres'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Limon'), 'Talamanca'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Limon'), 'Matina'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Limon'), 'Guacimo');
		
Select * from Cantones


INSERT INTO Distritos(IdProvincia, IdCanton, DescripcionDistrito)
VALUES  ((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Alajuelita'), 'Alajuelita'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Alajuelita'), 'San Antonio'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Aserrí'), 'Aserrí'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Aserrí'), 'Salitrillos'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Curridabat'), 'Curridabat'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Curridabat'), 'Tirrases'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Desamparados'), 'Desamparados'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Desamparados'), 'Los Guido'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Desamparados'), 'San Antonio'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Desamparados'), 'San Rafael Abajo'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Desamparados'), 'San Rafael Arriba'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Escazú'), 'Escazú'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Escazú'), 'San Antonio'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Goicoechea'), 'Calle Blancos'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Montes de Oca'), 'Sabanilla'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Montes de Oca'), 'San Pedro'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Mora'), 'Ciudad Colón'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Perez Zeledon'), 'San Isidro de El General'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Central'), 'Hatillo'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Central'), 'Pavas'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Central'), 'San Francisco de Dos Ríos'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Central'), 'Uruca'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Central'), 'Zapote'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Santa Ana'), 'Pozos'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Tibas'), 'León XIII'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Tibas'), 'San Juan'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'San Jose'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Vasquez de Coronado'), 'Dulce Nombre de Jesús'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Alajuela'), 'Alajuela'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Alajuela'), 'Guácima'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Alajuela'), 'Río Segundo'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Alajuela'), 'Garita'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'San Ramón'), 'San Ramón'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'San Ramón'), 'Peñas Blancas'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'San Ramón'), 'San Juan'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Grecia'), 'Grecia'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Grecia'), 'San José'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Atenas'), 'Atenas'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Naranjo'), 'Naranjo'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Naranjo'), 'San Miguel'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Naranjo'), 'Buenos Aires'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Poás'), 'San Pedro'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Orotina'), 'Orotina'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'San Carlos'), 'Pital'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'San Carlos'), 'La Fortuna'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Zarcero'), 'Zarcero'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Valverde Vega'), 'Sarchi'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Upala'), 'Upala'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Los chiles'), 'Caño Negro'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Alajuela'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Gautuso'), 'San Rafael'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Cartago'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Cartago'), 'San Nicolás'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Cartago'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Cartago'), 'Carmen'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Cartago'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Cartago'), 'Tierra Blanco'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Cartago'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Paraiso'), 'Paraiso'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Cartago'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Paraiso'), 'Orosi'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Cartago'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Jiménez'), 'Tucurrique'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Cartago'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Jiménez'), 'Pejibaye'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Cartago'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Turrialba'), 'San Nicolás'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Cartago'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Turrialba'), 'Chirripo'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Cartago'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Oreamuno'), 'San Rafael'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Cartago'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'El Guarco'), 'Tejar'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Heredia'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Heredia'), 'Heredia'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Heredia'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Heredia'), 'Mercedes'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Heredia'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Barva'), 'Barva'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Heredia'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Barva'), 'San Pablo'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Heredia'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Santo Domingo'), 'Santo Domingo'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Heredia'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Santo Domingo'), 'San Vicente'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Heredia'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Santo Domingo'), 'San Rosa'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Heredia'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Santa Barbara'), 'Santa Barbara'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Heredia'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Santa Barbara'), 'San Juan'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Heredia'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'San Rafael'), 'San Rafael'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Heredia'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'San Rafael'), 'Ángeles'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Heredia'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'San Isidro'), 'San Isidro'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Heredia'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'San Isidro'), 'Concepcion'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Heredia'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Belen'), 'San Antonio'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Heredia'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Belen'), 'San Asuncion'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Heredia'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Sarapiquí'), 'Puerto Viejo'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Heredia'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Sarapiquí'), 'La Virgen'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Guanacaste'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Liberia'), 'Liberia'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Guanacaste'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Liberia'), 'Nicoya'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Guanacaste'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Santa Cruz'), 'Santa Cruz'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Guanacaste'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Santa Cruz'), 'Tamarindo'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Guanacaste'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Bagaces'), 'Bagaces'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Guanacaste'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Carrillo'), 'Sardinal'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Guanacaste'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Cañas'), 'Cañas'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Guanacaste'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Abangares'), 'Las Juntas'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Guanacaste'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Tilaran'), 'Tilarán'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Guanacaste'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Nandayure'), 'Zapotal'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Guanacaste'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'La Cruz'), 'La Cruz'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Guanacaste'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'La Cruz'), 'Santa Cecilia'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Puntarenas'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Puntarenas'), 'Puntarenas'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Puntarenas'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Puntarenas'), 'Manzanillo'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Puntarenas'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Puntarenas'), 'Barranca'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Puntarenas'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Puntarenas'), 'Monteverde'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Puntarenas'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Puntarenas'), 'Cobano'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Puntarenas'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Puntarenas'), 'Chacarita'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Puntarenas'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Puntarenas'), 'El Roble'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Puntarenas'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Esparza'), 'Buenos Aires'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Puntarenas'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Esparza'), 'San Jeronimo'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Puntarenas'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Bueno Aires'), 'Buenos Aires'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Puntarenas'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Bueno Aires'), 'Boruca'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Puntarenas'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Osa'), 'Cortes'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Puntarenas'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Osa'), 'Bahía Ballena'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Puntarenas'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Quepos'), 'Quepos'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Puntarenas'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Golfito'), 'Golfito'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Puntarenas'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Golfito'), 'Puerto Jimenez'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Puntarenas'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Coto Brus'), 'Coto Brus'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Puntarenas'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Coto Brus'), 'Sabalito'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Puntarenas'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Parrita'), 'Parrita'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Puntarenas'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Corredores'), 'Corredor'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Puntarenas'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Garabito'), 'Jaco'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Puntarenas'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Garabito'), 'Tárcoles'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Limon'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Limon'), 'Limon'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Limon'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Limon'), 'Valle la Estrella'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Limon'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Pococi'), 'Guápiles'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Limon'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Pococi'), 'Cariari'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Limon'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Pococi'), 'Colorado'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Limon'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Siquirres'), 'Siquirres'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Limon'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Talamanca'), 'Sixaola'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Limon'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Matina'), 'Matina'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Limon'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Matina'), 'Batan'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Limon'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Guacimo'), 'Guacimo'),
		((Select idProvincia from dbo.Provincias where DescripcionProvincia = 'Limon'), (Select IdCanton from dbo.Cantones Where DescripcionCanton = 'Guacimo'), 'Mercedes');

select * from Distritos


INSERT INTO Direcciones (IdProvincia, IdCanton, IdDistrito, Carnet, Descripcion)
VALUES  (1, 1, 1, 1, 'Alajuelita centro'),
		(1, 1, 2, 2, 'Del parque de San Antonio, 50 mts sur, casa verde'),
		(1, 2, 3, 3, 'De la casa del dios Cristhian Garita, la siguiente.'),
		(1, 3, 5, 4, 'Del cenmenterio 25 mts sur y 50 este, en los multifamiliares el corral, edificil H');

select * from Direcciones


INSERT INTO TipoCarrera(Codigo_Carrera, NombreCarrera)
VALUES  ('Period', 'Periodismo'),
		('IngInfo', 'Ingenieria Informatica');

Select * from TipoCarrera


INSERT INTO Carrera (Codigo_Carrera, Carnet)
VALUES ('IngInfo', 1),
		('IngInfo', 2),
		('Period', 3),
		('Period', 4);

Select * from Carrera


INSERT INTO PlanEstudio (Codigo_Carrera)
VALUES ('Period'),
	   ('IngInfo');

Select * from PlanEstudio

		
INSERT INTO Curso (Codigo_Curso, Codigo_Plan, NombreCurso, Cuatrimestre, Creditos)	
VALUES  ('PGI01', 1, 'INGLES I', 1, 4),
		('PG002', 1, 'INTRODUCCIÓN A LA INVESTIGACIÓN Y ESTADISTICA', 1, 4),
		('PE-01', 1, 'INTRODUCCION AL PERIODISMO', 1, 4),
		('PG003', 1, 'TECNICAS DE COMUNICACION I', 1, 4),
		('HI-03', 1, 'HISTORIA DE COSTA RICA', 2, 4),
		('PGI02', 1, 'INGLES II', 2, 4),
		('PII08', 1, 'INTROD. AL PROCESAMIENTO DE DATOS (HERR. COMPUTACIONALES)', 2, 4),
		('PE-21', 1, 'TECNICAS DE REDACCION PERIODIST.', 2, 4),
		('PE-52', 1, 'GENEROS PERIODISTICOS', 3, 4),
		('PGI03', 1, 'INGLES III', 3, 4),
		('PE-60', 1, 'PERIOD. RADIOF. Y TECN. LOCUCION', 3, 4),
		('PE-30', 1, 'PROGRAMACION EN INTERNET', 3, 4),
		('PE-71', 1, 'OPINION PUBLICA Y COMUNIC. PERIOD.', 4, 4),
		('PE-35', 1, 'PERIODISMO EN INTERNET', 4, 4),
		('PE-40', 1, 'PERIODISMO ESCRITO', 4, 4),
		('PE-50', 1, 'PRODUCCION EN PRENSA', 4, 4),
		('PC-25', 1, 'COMUNICACION ORGANIZACIONAL', 5, 4),
		('PE-81', 1, 'ETICA Y LEGISLACION P/PERIOD.', 5, 4),
		('PEL65', 1, 'FOTOGRAFIA PERIODISTICA', 5, 4),
		('PE-61', 1, 'PERIODISMO TELEVISIVO', 5, 4),
		('PE-72', 1, 'ADMINIST. DE EMPRESAS PERIODIST.', 6, 4),
		('PE-62', 1, 'PERIODISMO ECONOMICO', 6, 4),
		('PE-63', 1, 'PERIODISMO POLITICO', 6, 4),
		('PEL61', 1, 'PRODUCCION EN RADIO', 6, 4),
		('PE-65', 1, 'PERIODISMO DEPORTIVO', 7, 4),
		('PE-64', 1, 'PERIODISMO SUCESOS', 7, 4),
		('PE-66', 1, 'PERIODISMO Y TEMATICA SOCIAL', 7, 4),
		('PC-27', 1, 'TALLER DE RELACIONES PUBLICAS', 7, 4),
		('TGPER1', 1, 'TALLER INT. GRADUACION', 7, 0),
		('PE-82', 1, 'PERIODISMO INTERPRETATIVO', 8, 4),
		('PE-70', 1, 'PERIODISMO INVESTIGATIVO', 8, 4),
		('PE-83', 1, 'PRACTICA PROFESIONAL', 8, 4),
		('PE-88', 1, 'SEMINARIO DE GRADUACION', 8, 4),
		('AE-10', 2, 'FUNDAMENTOS DE ADMINISTRACION', 1, 4),
		('IS-10', 2, 'INTRODUCCION A LA COMPUTACION', 1, 4),
		('PMA01', 2, 'MATEMÁTICAS PARA CIENCIAS DE LA ECONOMÍA (MAT.I)', 1, 4),
		('PG333', 2, 'TECNICAS DE COMUNICACION I', 1, 4),
		('AE-05', 2, 'CONTABILIDAD I', 2, 4),
		('PGI99', 2, 'INGLES I', 2, 4),
		('MA-15', 2, 'MATEMATICA II (CALCULO PARA CIENCIAS DE LA ECONOMÍA)', 2, 4),
		('IS-11', 2, 'PROGRAMACION I', 2, 4),
		('MA-20', 2, 'CALCULO I', 3, 4),
		('PAC03', 2, 'CONTABILIDAD DE COSTOS (COSTOS I)', 3, 4), 
		('IS-21', 2, 'ESTRUCTURAS Y ALGORITMOS', 3, 4),
		('IS-12', 2, 'PROGRAMACION II', 3, 4),
		('MA-25', 2, 'CALCULO II', 4, 4),
		('PII01', 2, 'DISEÑO DIGITAL Y MICROPROCESADORES (ELECTRONICA III)', 4, 4),
		('IS28L', 2, 'DISEÑO DIGITAL Y MICROPROCESADORES (LAB)', 4, 4),
		('PII07', 2, 'ESTRUC. ARCHIVOS (B. DATOS I)', 4, 4),
		('IS-23', 2, 'PROGRAMACION III', 4, 4),
		('PII06', 2, 'ADMIN. DIS. B.D. (B. DATOS II)', 5, 4),
		('AE-19', 2, 'ECONOMIA I (TEÓRIA ECONÓMICA)', 5, 4),
		('AE-25', 2, 'MERCADEO I', 5, 4),
		('IS-25', 2, 'SISTEMAS OPERATIVOS I', 5, 4),
		('FI-05', 2, 'FINANZAS PARA INGENIERIA', 6, 4),
		('PG001', 2, 'PROBABILIDAD Y ESTADISTICA (ESTADISTICA DESCRIPTIVA (P/TURISMO))', 6, 4),
		('IS-39', 2, 'PROGRAMACION IV', 6, 4),
		('IS-26', 2, 'SISTEMAS OPERATIVOS II', 6, 4),
		('PII02', 2, 'INVESTIGACION DE OPERACIONES I', 7, 4),
		('IS-41', 2, 'LENGUAJES DE 4TA. GENERACION', 7, 4),
		('IS-36', 2, 'PROGRAMACION SISTEMAS COMPUTACIONALES', 7, 4),
		('SIS.INFO.I', 2, 'SISTEMAS DE INFORMACION I (INGENIERIA DE SOFTWARE I)', 7, 4),
		('IS-29', 2, 'ADMINISTRACION DE PROYECTOS', 8, 4),
		('PII03', 2, 'INVESTIGACION DE OPERACIONES II', 8, 4),
		('PII04', 2, 'REDES DE COMPUTADORES(TELEPROCESOS Y SISTEMAS DISTIBUTIVOS I)', 8, 4),
		('SIS.INFO.II', 2, 'SISTEMAS DE INFORMACION II (INGENIERIA DE SOFTWARE II)', 8, 4),
		('TGINF1', 2, 'TALLER INT. GRADUACION', 8, 0),
		('IS-31', 2, 'ADMIN. DE CENTROS DE COMPUTO', 9, 4),
		('IS-35', 2, 'AUDITORIA DE SISTEMAS', 9, 4),
		('IS-45', 2, 'SEMINARIO DE GRADUACION', 9, 0),
		('SIS.INFO.III', 2, 'SISTEMAS DE INFORMACION III (INGENIERÍA DEL SOFTWARE III)', 9, 4),
		('IS-38', 2, 'TOPICOS ESPECIALES EN COMPUT.', 9, 4);

Select * from Curso


-- aprovado, reprovado, aplazado, No cursado
INSERT INTO InformacionCurso (Codigo_Curso, Carnet, EstadoCurso, Nota)
VALUES  --('AE-10', 1, 'Aprovado', 90),
		('IS-10', 1, 'Aprovado', 86),
		('PMA01', 1, 'Aprovado', 88),
		('PG333', 1, 'Aprovado', 97),
		('AE-05', 1, 'Aprovado', 79),
		('PGI99', 1, 'Aprovado', 95),
		('MA-15', 1, 'Aprovado', 85),
		('IS-11', 1, 'Aprovado', 78),
		('MA-20', 1, 'Aprovado', 80),
		('PAC03', 1, 'Reprovado', 65), 
		('IS-21', 1, 'Aprovado', 72),
		('IS-12', 1, 'Aprovado', 85),
		('MA-25', 1, 'No cursado', ''),
		('PII01', 1, 'No cursado', ''),
		('IS28L', 1, 'No cursado', ''),
		('PII07', 1, 'No cursado', ''),
		('IS-23', 1, 'No cursado', ''),
		('PII06', 1, 'No cursado', ''),
		('AE-19', 1, 'No cursado', ''),
		('AE-25', 1, 'No cursado', ''),
		('IS-25', 1, 'No cursado', ''),
		('FI-05', 1, 'No cursado', ''),
		('PG001', 1, 'No cursado', ''),
		('IS-39', 1, 'No cursado', ''),
		('IS-26', 1, 'No cursado', ''),
		('PII02', 1, 'No cursado', ''),
		('IS-41', 1, 'No cursado', ''),
		('IS-36', 1, 'No cursado', ''),
		('SIS.INFO.I', 1, 'No cursado', ''),
		('IS-29', 1, 'No cursado', ''),
		('PII03', 1, 'No cursado', ''),
		('PII04', 1, 'No cursado', ''),
		('SIS.INFO.II', 1, 'No cursado', ''),
		('TGINF1', 1, 'No cursado', ''),
		('IS-31', 1, 'No cursado', ''),
		('IS-35', 1, 'No cursado', ''),
		('IS-45', 1, 'No cursado', ''),
		('SIS.INFO.III', 1, 'No cursado', ''),
		('IS-38', 1, 'No cursado', ''),
        ('AE-10', 2, 'Aprovado', 80),
		('IS-10', 2, 'Aprovado', 80),
		('PMA01', 2, 'Aprovado', 70),
		('PG333', 2, 'Aprovado', 99),
		('AE-05', 2, 'Aprovado', 79),
		('PGI99', 2, 'Aprovado', 85),
		('MA-15', 2, 'Aprovado', 85),
		('IS-11', 2, 'Aprovado', 78),
		('MA-20', 2, 'Aprovado', 80),
		('PAC03', 2, 'Aprovado', 74), 
		('IS-21', 2, 'Aprovado', 72),
		('IS-12', 2, 'Aprovado', 89),
		('MA-25', 2, 'Aprovado', 77),
		('PII01', 2, 'Aprovado', 90),
		('IS28L', 2, 'Aprovado', 75),
		('PII07', 2, 'Aprovado', 78),
		('IS-23', 2, 'Aprovado', 85),
		('PII06', 2, 'Aprovado', 73),
		('AE-19', 2, 'Aprovado', 70),
		('AE-25', 2, 'Aprovado', 86),
		('IS-25', 2, 'Aprovado', 83),
		('FI-05', 2, 'Aprovado', 91),
		('PG001', 2, 'Aprovado', 75),
		('IS-39', 2, 'Aprovado', 73),
		('IS-26', 2, 'Aprovado', 80),
		('PII02', 2, 'Aprovado', 83),
		('IS-41', 2, 'Aprovado', 78),
		('IS-36', 2, 'Aprovado', 73),
		('SIS.INFO.I', 2, 'Aprovado', 72),
		('IS-29', 2, 'Aprovado', 81),
		('PII03', 2, 'Aprovado', 74),
		('PII04', 2, 'Aprovado', 88),
		('SIS.INFO.II', 2, 'Aprovado', 90),
		('TGINF1', 2, 'Aprovado', 70),
		('IS-31', 2, 'No cursado', ''),
		('IS-35', 2, 'No cursado', ''),
		('IS-45', 2, 'No cursado', ''),
		('SIS.INFO.III', 2, 'Aprovado', 72),
		('IS-38', 2, 'No cursado', ''),
		('PGI01', 3, 'Aprovado', 75),
		('PG002', 3, 'Aprovado', 78),
		('PE-01', 3, 'Aprovado', 79),
		('PG003', 3, 'Aprovado', 70),
		('HI-03', 3, 'Reprovado', 65),
		('PGI02', 3, 'Reprovado', 64),
		('PII08', 3, 'Reprovado', 68),
		('PE-21', 3, 'No cursado', ''),
		('PE-52', 3, 'No cursado', ''),
		('PGI03', 3, 'No cursado', ''),
		('PE-60', 3, 'No cursado', ''),
		('PE-30', 3, 'No cursado', ''),
		('PE-71', 3, 'No cursado', ''),
		('PE-35', 3, 'No cursado', ''),
		('PE-40', 3, 'No cursado', ''),
		('PE-50', 3, 'No cursado', ''),
		('PC-25', 3, 'No cursado', ''),
		('PE-81', 3, 'No cursado', ''),
		('PEL65', 3, 'No cursado', ''),
		('PE-61', 3, 'No cursado', ''),
		('PE-72', 3, 'No cursado', ''),
		('PE-62', 3, 'No cursado', ''),
		('PE-63', 3, 'No cursado', ''),
		('PEL61', 3, 'No cursado', ''),
		('PE-65', 3, 'No cursado', ''),
		('PE-64', 3, 'No cursado', ''),
		('PE-66', 3, 'No cursado', ''),
		('PC-27', 3, 'No cursado', ''),
		('TGPER1', 3, 'No cursado', ''),
		('PE-82', 3, 'No cursado', ''),
		('PE-70', 3, 'No cursado', ''),
		('PE-83', 3, 'No cursado', ''),
		('PE-88', 3, 'No cursado', ''),
		('PGI01', 4, 'Aprovado', 88),
		('PG002', 4, 'Aprovado', 90),
		('PE-01', 4, 'No cursado', ''),
		('PG003', 4, 'No cursado', ''),
		('HI-03', 4, 'No cursado', ''),
		('PGI02', 4, 'No cursado', ''),
		('PII08', 4, 'No cursado', ''),
		('PE-21', 4, 'No cursado', ''),
		('PE-52', 4, 'No cursado', ''),
		('PGI03', 4, 'No cursado', ''),
		('PE-60', 4, 'No cursado', ''),
		('PE-30', 4, 'No cursado', ''),
		('PE-71', 4, 'No cursado', ''),
		('PE-35', 4, 'No cursado', ''),
		('PE-40', 4, 'No cursado', ''),
		('PE-50', 4, 'No cursado', ''),
		('PC-25', 4, 'No cursado', ''),
		('PE-81', 4, 'No cursado', ''),
		('PEL65', 4, 'No cursado', ''),
		('PE-61', 4, 'No cursado', ''),
		('PE-72', 4, 'No cursado', ''),
		('PE-62', 4, 'No cursado', ''),
		('PE-63', 4, 'No cursado', ''),
		('PEL61', 4, 'No cursado', ''),
		('PE-65', 4, 'No cursado', ''),
		('PE-64', 4, 'No cursado', ''),
		('PE-66', 4, 'No cursado', ''),
		('PC-27', 4, 'No cursado', ''),
		('TGPER1', 4, 'No cursado', ''),
		('PE-82', 4, 'No cursado', ''),
		('PE-70', 4, 'No cursado', ''),
		('PE-83', 4, 'No cursado', ''),
		('PE-88', 4, 'No cursado', '');

Select * from InformacionCurso


INSERT INTO Requisitos(Requisitos, Codigo_Info)
VALUES()









